config/routes.rb
Myinverts::Application.routes.draw do
  resources :subscriptions

  devise_for :users

  root 'welcome#index'

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subscription }
      else
        format.html { render action: 'new' }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:name, :price, :stripe_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myinverts</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :stripe_id %><br>
    <%= f.text_field :stripe_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Stripe</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.name %></td>
        <td><%= subscription.price %></td>
        <td><%= subscription.stripe_id %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subscription.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @subscription.price %>
</p>

<p>
  <strong>Stripe:</strong>
  <%= @subscription.stripe_id %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
		<title>Product Splash</title>
		<link rel="stylesheet" type="text/css" href="/welcome/styles.css" />
		<link rel="stylesheet" href="/welcome/nivoslider/nivo-slider.css" type="text/css" media="screen" />
		<link rel="stylesheet" href="/welcome/nivoslider/themes/default/default.css" type="text/css" media="screen" />
		<link rel="stylesheet" href="/welcome/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
	</head>


	<body>

		<div class="container">
			<div class="header">
				<h1>Zoo Tracker</h1>
				<div class="get-it-buttons">
					<a href="#" class="free-trial-button">Free Trial</a>
					<a href="#" class="buy-it-button">Buy It Now</a>
				</div>
			</div>
			<div class="intro">
				<h2>Tracking Manager</h2>
				<p>Promote your products or apps in style with this free template from MediaLoot</p>


				<div class="slider-wrapper theme-default mask-container-large">
				    <div id="slider" class="nivoSlider">
				        <img src="/welcome/images/image-large-1.jpg" alt="" />
				        <img src="/welcome/images/image-large-2.jpg" alt="" />
				        <img src="/welcome/images/image-large-3.jpg" alt="" />
				        <img src="/welcome/images/image-large-4.jpg" alt="" />
				    </div>
				    <div class="mask-gloss-large"></div>
				</div>
			</div>
			<div class="divider-2"></div>
			<div class="top-features">
				<h3>Top Features</h3>
				<div class="inset-top"></div>
				<div class="inset">
					<div class="row"><!--Start of Row-->

						<div class="col"><!--Start of Feature-->
							<div class="feature-image">
								<a rel="fancybox" href="/welcome/images/image-large-1.jpg">
									<div class="mask-container-thumbnail">
										<img src="/welcome/images/image-thumbnail-1.jpg" alt="" />
										<div class="mask-gloss-thumbnail"></div>
									</div>
								</a>
							</div>
							<div class="description">
								<h4>Lorem Ipsum</h4>
								<p>Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Etiam porta sem malesuada magna mollis euismod.</p>

								<p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>

								<p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
							</div>
						</div><!--End of Feature-->

						<div class="col"><!--Start of Feature-->
							<div class="feature-image">
								<a rel="fancybox" href="/welcome/images/image-large-2.jpg">
									<div class="mask-container-thumbnail">
										<img src="/welcome/images/image-thumbnail-2.jpg" alt="" />
										<div class="mask-gloss-thumbnail"></div>
									</div>
								</a>
							</div>
							<div class="description">
								<h4>Lorem Ipsum</h4>
								<p>Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Etiam porta sem malesuada magna mollis euismod.</p>

								<p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>

								<p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
							</div>
						</div><!--End of Feature-->

						<br class="clear" />
					</div><!--End of Row-->

					<div class="row"><!--Start of Row-->

						<div class="col"><!--Start of Feature-->
							<div class="feature-image">
								<a rel="fancybox" href="/welcome/images/image-large-3.jpg">
									<div class="mask-container-thumbnail">
										<img src="/welcome/images/image-thumbnail-3.jpg" alt="" />
										<div class="mask-gloss-thumbnail"></div>
									</div>
								</a>
							</div>
							<div class="description">
								<h4>Lorem Ipsum</h4>
								<p>Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Etiam porta sem malesuada magna mollis euismod.</p>

								<p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>

								<p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
							</div>
						</div><!--End of Feature-->

						<div class="col"><!--Start of Feature-->
							<div class="feature-image">
								<a rel="fancybox" href="/welcome/images/image-large-4.jpg">
									<div class="mask-container-thumbnail">
										<img src="/welcome/images/image-thumbnail-4.jpg" alt="" />
										<div class="mask-gloss-thumbnail"></div>
									</div>
								</a>
							</div>
							<div class="description">
								<h4>Lorem Ipsum</h4>
								<p>Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Etiam porta sem malesuada magna mollis euismod.</p>

								<p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>

								<p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
							</div>
						</div><!--End of Feature-->

						<br class="clear" />
					</div><!--End of Row-->


				</div>
				<div class="inset-btm"></div>
			</div>

			<div class="testimonials">
				<h3>Testimonials</h3>

				<div class="quote"><!--Start of Quote-->
					<img src="/welcome/images/quotation-mark.png" alt="quotation mark" class="quotation-mark" />
					<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla vitae elit libero, a pharetra augue.</p>

					<p>Nulla vitae elit libero, a pharetra augue. Vestibulum id ligula porta felis euismod semper. Curabitur blandit tempus porttitor. Etiam porta sem malesuada magna mollis euismod. </p>

					<p><strong>Full Name</strong></p>
				</div><!--End of Quote-->

				<div class="quote"><!--Start of Quote-->
					<img src="/welcome/images/quotation-mark.png" alt="quotation mark" class="quotation-mark" />
					<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla vitae elit libero, a pharetra augue.</p>

					<p>Nulla vitae elit libero, a pharetra augue. Vestibulum id ligula porta felis euismod semper. Curabitur blandit tempus porttitor. Etiam porta sem malesuada magna mollis euismod. </p>

					<p><strong>Full Name</strong></p>
				</div><!--End of Quote-->

				<br class="clear" />

			</div>

			<div class="footer">
				<p>Copyright 2011 <strong>Product Name</strong>. All Rights Reserved.
				<div class="get-it-buttons">
					<a href="#" class="free-trial-button">Free Trial</a>
					<a href="#" class="buy-it-button">Buy It Now</a>
				</div>
			</div>

		</div>

		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
		<script type="text/javascript" src="/welcome/nivoslider/jquery.nivo.slider.pack.js"></script>
		<script type="text/javascript" src="/welcome/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
		<script type="text/javascript" src="/welcome/fancybox/jquery.easing-1.4.pack.js"></script>
		<script type="text/javascript" src="/welcome/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>

		<script type="text/javascript">
		$(window).load(function() {
		    $('#slider').nivoSlider();
		});
		</script>

		<script type="text/javascript">
				$(window).load(function() {
				    $("*[rel=fancybox]").fancybox();
				});
		</script>


	</body>

</html>